title: "Red Pages"
description: "Notes and development"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache

# Settings
markdown: kramdown
show_date: true

# Navigation
collections:
  posts:
    output: true

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: false

